services:
  app:
    container_name: books_task_app
    build: .
    depends_on:
      - db
    command: bash -c '
      while !</dev/tcp/db/$DB_PORT; do
      echo "Waiting for PostgreSQL to be ready...";
      sleep 1;
      done;
      alembic upgrade head &&
      uvicorn main:app --host 0.0.0.0 --port 8000'
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always

  db:
    container_name: books_task_postgres
    image: postgres:15
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data: