"""third

Revision ID: 031b490b27e5
Revises: d5c29e65f7e1
Create Date: 2025-01-14 22:36:00.577810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '031b490b27e5'
down_revision: Union[str, None] = 'd5c29e65f7e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book_loans', 'return_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_unique_constraint(None, 'genres', ['name'])
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'READER', name='role'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'READER', name='role'),
               nullable=True)
    op.drop_constraint(None, 'genres', type_='unique')
    op.alter_column('book_loans', 'return_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
