"""fourth

Revision ID: a078bfb8d530
Revises: 031b490b27e5
Create Date: 2025-01-15 15:00:55.653676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a078bfb8d530'
down_revision: Union[str, None] = '031b490b27e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_loans', sa.Column('estimated_return_date', sa.Date(), nullable=False))
    op.add_column('book_loans', sa.Column('actual_return_date', sa.Date(), nullable=True))
    op.drop_column('book_loans', 'return_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_loans', sa.Column('return_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('book_loans', 'actual_return_date')
    op.drop_column('book_loans', 'estimated_return_date')
    # ### end Alembic commands ###
