"""second

Revision ID: d5c29e65f7e1
Revises: 002445500ae8
Create Date: 2025-01-13 16:33:01.815060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5c29e65f7e1'
down_revision: Union[str, None] = '002445500ae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authors', 'biography',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('authors', 'birth_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('books', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('books', 'publication_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('books', 'available_copies',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'READER', name='role'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'READER', name='role'),
               nullable=False)
    op.alter_column('books', 'available_copies',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('books', 'publication_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('books', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('authors', 'birth_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('authors', 'biography',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
